source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'

target 'IAR-DropIn_Example' do
  use_frameworks!
  inhibit_all_warnings!  # ignore warnings emmited from pod sources
  # pod 'IAR-DropIn', :path => '../'
  pod 'ImagineAR-UI',  '1.6.18'

  target 'IAR-DropIn_Tests' do
    inherit! :search_paths

  end
end

post_install do |installer|
	installer.pods_project.build_configurations.each do |config|
		config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
		config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
	end
  
	installer.pods_project.targets.each do |target|
	  target.build_configurations.each do |config|
		config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
	  end
	end

	installer.generated_projects.each do |project|
		project.targets.each do |target|
			target.build_configurations.each do |config|
				config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
			 end
		end
	end
end
