# Remove line below before releasing
source 'https://github.com/ImagineAR/IAR-SDK-Beta-Podspecs.git'
source 'https://cdn.cocoapods.org/'
platform :ios, '13.0'

def pod_sampleApp
  # https://github.com/onevcat/Kingfisher
  # Kingfisher is an image-centric library: used in the sample app for
  # filesystem caching, download management and jpg progressive loading
  pod 'Kingfisher',         '7.0.0'

  #pod_core
  pod_core_beta
end

def pod_core
  pod 'ImagineAR-Core',     '1.6.9'
end

def pod_core_beta
  pod 'IAR-Core',           '1.6.10-beta1'
end

def pod_core_local
  pod 'IAR-Core',     :path => '../../iar-sdk-ios'
end

target 'IAR-CoreSDK-Sample' do
  use_frameworks!
  inhibit_all_warnings!  # ignore warnings emmited from pod sources
  pod_sampleApp

  target 'IAR-CoreSDK-SampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IAR-CoreSDK-SampleUITests' do
    # Pods for testing
  end
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
