# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs unit tests on the Core Sample"
  lane :unit_test do
    run_tests()
  end

  lane :adhoc do

    import_certificate(
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      certificate_path: '../Certificates.p12',
      certificate_password: ENV["CERTIFICATE_PASSWORD"] || "default"
    )

    gym(export_method: "ad-hoc", configuration: "Release", scheme: "IAR-CoreSDK-Sample")
    # appcenter_upload(
    #   api_token: ENV["APPCENTER_API_TOKEN"],
    #   owner_name: "ENV["OWNER_NAME"]",
    #   owner_type: "user",
    #   destinations: "Collaborators",
    #   app_name: "Famedays-iOS",
    #   notify_testers: true
    # )
  end
end
