# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs unit tests on the Core Sample"
  lane :unit_test do
    run_tests()
  end

  lane :adhoc do
    match(type: "adhoc")
    gym(export_method: "ad-hoc",  configuration: "Release", scheme: "IAR-CoreSDK-Sample")
    appcenter_upload(
      api_token: ENV["APPCENTER_API_TOKEN"],
      owner_name: ENV["OWNER_NAME"],
      owner_type: "user",
      destinations: "Collaborators",
      app_name: "IAR-CoreSDK-Sample",
      notify_testers: true
    )
  end
end
